# pom.xml로 무엇을 쓸지 템플릿을 결정했다면
# application.yml은 어떻게 돌릴지 결정

server:
    port: 8080 # http 포트 설정

# server:
#    port: 8443 # https 포트 설정
#    ssl:
#        enabled: true
#        key-store: classpath:ssl/localhost.p12
#        key-store-password: changeit
#        key-store-type: PKCS12
#        key-alias: projectcairo-local

spring:
  thymeleaf:
    cache: false   # 개발 중 템플릿 캐시 끔
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.219.103:1521/XEPDB1 # 윈도우에서 맥북 JunDB로 접속(localhost 아님)
    username: sangzoon0102
    password: seoul01!!cns
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG
